### ISSUE TITLE
[3.0.1.102-dev] Crash on world load

### ISSUE THREAD

**Issue by JasonMcRay** [ollieread/TechnoMagi#12]
I grabbed the latest dev build to test it out, but unfortunately I have encounter a crash. Tested on already created world and also new world.
Crashlog: http://pastebin.com/VFB4jZnL

EnndsCore: 2.4.0.119-b
TechnoMagi: 3.0.1.102-dev
Forge version: 1232

**Comment by Hades99** [comment]
Try removing optifine before posting any crash report. Also, were you using any other mods.

**Comment by JasonMcRay** [comment]
Removed Optifine, still same issue occuring.
Was also using liteloader with matmos. Removed that and still I am not able to create new world.
Mod list of my pack can be found here: https://github.com/JasonMcRay/InfiTech-1.7/tree/master/mods

**Comment by Hades99** [comment]
problem is Thaumcraft and/or BoP

On Wed, Feb 4, 2015 at 2:51 PM, Jason McRay <notifications@github.com>
wrote:

> Removed Optifine, still same issue occuring.
> Was also using liteloader with matmos. Removed that and still I am not
> able to create new world.
> Mod list of my pack can be found here:
> https://github.com/JasonMcRay/InfiTech-1.7/tree/master/mods
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ollieread/TechnoMagi/issues/12#issuecomment-72936252>.
>



-- 
Eli

**Comment by ollieread** [comment]
This was actually a bug with an old build that should have since been fixed. I'm currently going through a huge refactoring, including some changes to the fundamentals of the mod.
