### ISSUE TITLE
Broken GUI

### ISSUE THREAD

**Issue by sProgg** [ollieread/TechnoMagi#14]
Seems the Path GUI doesn't work, clicking on the button to choose does nothing.

**Comment by ollieread** [comment]
Do you get anything in the console?

**Comment by sProgg** [comment]
I can check, hang on.

**Comment by ollieread** [comment]
By path do you mean Specialisation? And which button is it that isn't working, the 'Choose Specialisation' button or the individual Specialisation buttons?
