### ISSUE TITLE
NPE Upon Right Clicking Air with Guardian and Scholar's Staff

### ISSUE THREAD

**Issue by SabreProjects** [ollieread/TechnoMagi#16]
http://pastebin.com/WSSLNDdD

Forge Version: 1.7.10-10.13.2.1291
Mods Installed: CoFHCore-[1.7.10]3.0.0RC5-207
Technomagi-0.1.6-beta

Description: Upon right-clicking air with one of the aforementioned staves, the game encounters a NPE and crashes. This error does not occur when you right click a block, and although I haven't had the time to test it with the other specializations yet, I suspect that it this error will repeat with them as well.

**Comment by ollieread** [comment]
This should be fixed by build 7 if you could also confirm.

http://jenkins.ollieread.com/job/Technomagi-beta/7/

**Comment by SabreProjects** [comment]
I tested it, the fix is confirmed as NPE no longer occurs. 

Slightly off topic, I'm having some problems figuring out what to test now due to not knowing how to go through the research system. Any pointers towards the next thing you want tested?

**Comment by ollieread** [comment]
The main thing is to just start building, mining and playing, Providing that you've crafted yourself an interface, the events that are supposed to fire should fire. Without revealing all of the actions that need to be done to gain research, it's kind of hard, sorry, aha.
