### ISSUE TITLE
Divide By Zero!

### ISSUE THREAD

**Issue by sProgg** [ollieread/TechnoMagi#17]
http://p.pomf.se/6795

Trying to choose the Scholar path in the Nanite Interface GUI causes this.

**Comment by sProgg** [comment]
Edit: Might be a mod conflict with the Weather Mod.

**Comment by Anigmatics** [comment]
I've had this problem aswell, but I have no other mods installed.

**Comment by ollieread** [comment]
@Anigmatics Do you get the same error when creating a world? Exact same error?

**Comment by sProgg** [comment]
Creating a new world and doing it seems to erase the error. Note, don't uninstall and reinstall the mod on the same world.

**Comment by ollieread** [comment]
Ahh, that makes a bit more sense.

**Comment by sProgg** [comment]
It's more an issue of uninstalling an old version then installing a newer one without unloading old assets. Still, good to know.

**Comment by ollieread** [comment]
Well that should still not be the case, the problem is that it's not loading player data from NBT properly.
