### ISSUE TITLE
Bad sheep, bad!

### ISSUE THREAD

**Issue by sProgg** [ollieread/TechnoMagi#20]
Right-clicking a passive entity crashes the game, seems ot be a problem with an Event.

http://p.pomf.se/6826

Sorry about all the bug reports by the way.

Edit: Seems to only be a problem with an empty hand and only on sheep.

**Comment by ollieread** [comment]
No problem at all, it's good to find these, like I said, they're dev/beta builds so there are likely to be a few.

**Comment by ollieread** [comment]
I've found the problem, fixed locally and a new build will up later on today.
