### ISSUE TITLE
Mining Research Issue and others.

### ISSUE THREAD

**Issue by sProgg** [ollieread/TechnoMagi#22]
http://p.pomf.se/6987

Minor issues:

-Research bars no long go up no matter what I do, 
-No way to analyze things (Do I right-click dust with my staff?)? Or the events simply don't happen (see above).
-Textures missing, not a big problem.
-All staves make Nanite Farmland and take no damage. Not sure if intentional.

**Comment by ollieread** [comment]
Interesting error, will take a look into it. The error does explain the research bars not going up and the analysis is the next thing to be done, it's a machine that needs to be made.

Textures missing I'm aware of, and the nanite farmland shouldn't damage the stave, though only one specialisation should do that.

Clerics Staff - Turns grass/dirt into nanite farmland
Guardians Staff - Functions as a sword
Shadows Staff - Adds weakness to an enemy hit
Engineers Staff - Functions as a crescent hammer (currently broken)

**Comment by ollieread** [comment]
@sProgg When you say every different staff, do you mean everyone you make, or each of the different staves? Also, are you a cleric?

**Comment by sProgg** [comment]
Might just be a cleric staff, checking now.

**Comment by ollieread** [comment]
You have to be that speciality, as without using creative, there's no way to get one of the other staves.
