### ISSUE TITLE
Error using Phase Jump ability

### ISSUE THREAD

**Issue by ArbiterofTruth** [ollieread/TechnoMagi#25]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 5/6/15 10:07 AM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: -128
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.onUpdate(ClientPlayerAPI.java:6300)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.potion.PotionEffect.func_76455_a(PotionEffect.java:105)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:524)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:293)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityPlayerSP.localOnUpdate(EntityPlayerSP.java)
	at api.player.client.ClientPlayerAPI.onUpdate(ClientPlayerAPI.java:6300)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 234
	Entity Name: Hman745
	Entity's Exact location: 293.78, 76.62, -159.95
	Entity's Block location: World: (293,76,-160), Chunk: (at 5,4,0 in 18,-10; contains blocks 288,0,-160 to 303,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Hman745'/234, l='MpServer', x=293.78, y=76.62, z=-159.95]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (19,64,129), Chunk: (at 3,4,1 in 1,8; contains blocks 16,0,128 to 31,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 652394 game time, 973574 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntitySquid['Squid'/257, l='MpServer', x=358.50, y=61.00, z=-176.50], EntityItem['item.item.dyePowder.black'/258, l='MpServer', x=233.78, y=40.13, z=-127.84], EntityItem['item.item.dyePowder.black'/259, l='MpServer', x=237.34, y=40.13, z=-125.63], EntitySheep['Sheep'/260, l='MpServer', x=331.78, y=77.00, z=-215.50], EntityChicken['Chicken'/261, l='MpServer', x=367.56, y=62.15, z=-178.44], EntitySheep['Sheep'/262, l='MpServer', x=336.28, y=77.00, z=-220.19], EntitySheep['Sheep'/263, l='MpServer', x=364.22, y=63.00, z=-213.53], EntitySkeleton['Skeleton'/1449, l='MpServer', x=-27.78, y=-29.62, z=24.95], EntityClientPlayerMP['Hman745'/234, l='MpServer', x=293.78, y=76.62, z=-159.95], EntityGoblin['Hobgoblin'/236, l='MpServer', x=328.25, y=68.00, z=-156.50], EntityGoblin['Hobgoblin'/237, l='MpServer', x=281.88, y=77.00, z=-114.59], EntityGoblin['Hobgoblin'/238, l='MpServer', x=256.50, y=63.00, z=-140.97], EntityGoblin['Hobgoblin'/239, l='MpServer', x=257.44, y=64.00, z=-182.19], EntitySquid['Squid'/240, l='MpServer', x=255.50, y=56.06, z=-147.50], EntitySquid['Squid'/241, l='MpServer', x=250.94, y=53.31, z=-146.06], EntitySquid['Squid'/242, l='MpServer', x=241.50, y=57.34, z=-148.50], EntityGoblin['Hobgoblin'/244, l='MpServer', x=243.50, y=64.00, z=-154.06], EntitySquid['Squid'/245, l='MpServer', x=247.75, y=56.38, z=-130.97], EntitySquid['Squid'/246, l='MpServer', x=254.03, y=56.34, z=-142.88], EntityGoblin['Hobgoblin'/247, l='MpServer', x=336.78, y=74.00, z=-131.78], EntityItem['item.tile.sapling.oak'/248, l='MpServer', x=267.00, y=85.13, z=-200.97], EntitySquid['Squid'/249, l='MpServer', x=239.03, y=56.34, z=-142.34], EntityGoblin['Hobgoblin'/251, l='MpServer', x=282.09, y=64.00, z=-207.63], EntitySheep['Sheep'/252, l='MpServer', x=317.13, y=71.00, z=-218.66], EntityItem['item.tile.mushroom'/1662, l='MpServer', x=267.19, y=79.13, z=-197.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 452930600 bytes (431 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 59 mods loaded, 59 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WitchingGadgetsCore{1.1.6} [Witching Gadgets Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.2} [Treecapitator] ([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Automagy{0.23} [Automagy] (Automagy-1.7.10-0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.2-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botania{r1.6-187} [Botania] (Botania r1.6-187.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0RC4} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC4-204.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	dimdoors{2.2.5-test} [Dimensional Doors] (DimensionalDoors-2.2.5-test8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DummyCore{1.10} [Dummy Core] (DummyCore-1.10.1710.alpha.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Enchiridion2{2.0d} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	essentialcraft{4.4.1710.37} [Essential Craft 3] (EssentialCraft3-4.4.1710.47beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	essenthaum{1.1.1710.0} [Essential Thaumaturgy] (EssentialThaumaturgy-1.1.1710.11EC(4.4.1710.37)TC(4.2.3.5).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FinderCompass{1.7.10b} [Finder Compass] (FinderCompass-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ttCore{MC1.7.10-0.1.1-68} [ttCore] (ttCore-MC1.7.10-0.1.1-68.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	fluxedcrystals{0.0.5} [Fluxed-Crystals] (Fluxed-Crystals [0.0.5d].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forestry{3.0.0.125} [Forestry for Minecraft] (forestry_1.7.10-3.0.0.125.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	instahouse{7.0} [Insta House] (InstaHousev7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MagiaNaturalis{0.1.1} [§2Magia Naturalis] (MagiaNaturalis-1.7.10-0.1.2c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mariculture{1.7.10-1.2.4f} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RadixCore{2.0.0} [RadixCore] (RadixCore-1.7.10-2.0.0-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MCA{5.0.0-beta} [Minecraft Comes Alive] (MCA-1.7.10-5.0.0-beta-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.5.00} [Mystcraft] (mystcraft-1.7.10-0.11.5.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	newdawn{1710.1.0} [New Dawn] (newdawn-1710.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_Ruins{14.7} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Tails{1.7.10-1.3.1} [Tails] (Tails-1.7.10-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	tcnodetracker{1.0.4} [TC Node Tracker] (tcnodetracker-1.7.10-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Technomagi{0.5.1.28-alpha} [Technomagi] (Technomagi-0.5.1.28-alpha.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicHorizons{1.1.1} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TravellersGear{1.15.5} [Traveller's Gear] (TravellersGear-1.7.10-1.15.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.5} [The Twilight Forest] (twilightforest-1.7.10-2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WitchingGadgets{1.1.6} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore: -[1.7.10]3.0.0RC4-204
	ThermalFoundation: -[1.7.10]1.0.0RC4-58
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3345, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ollieread** [comment]
By the looks of it, that's an issue caused by SmartMoving. It's difficult to be certain, but I'm quite confident that this isn't a Technomagi bug. There is no potion id -128, the potion ids are given dynamically when it boots up (Technomagi at least) but the code that dynamically assigns the ids couldn't assign a negative integer.

    public static int nextPotionId()
    {
        for (int i = 0; i < Potion.potionTypes.length; i++) {
            if (Potion.potionTypes[i] == null) {
                return i;
            }
        }

        return -1;
    }

**Comment by ArbiterofTruth** [comment]
I don't have SmartMoving installed.

**Comment by ollieread** [comment]
Sorry, Galacticraft.

**Comment by ArbiterofTruth** [comment]
I don't have that installed either.

**Comment by ollieread** [comment]
Well, `api.player.client.ClientPlayerAPI.onUpdate` perfectly matches part of GC. Whatever you have installed that uses that, is what is causing the error.

**Comment by ArbiterofTruth** [comment]
Ah, this is a problem with PlayerApi, which I do have installed. I'll check
if there is an update to see if that fixes the crash otherwise I'll remove.

**Comment by ollieread** [comment]
Okay, let me know as I still can't find a solution for it.

**Comment by ollieread** [comment]
Any news on this?

**Comment by ArbiterofTruth** [comment]
Sorry for the delay. I updated PlayerAPI and I'm still got the same error
as well as when I removed it entirely. Still not sure what  is causing it.

**Comment by ollieread** [comment]
That is really strange, I can't for the life of me figure out why this is doing this.

**Comment by ArbiterofTruth** [comment]
I looked into part of the error (this in
particular:net.minecraft.client.entity.EntityClientPlayerMP) that I was
getting and it essentially said I was using a client-only mod on a server.
This doesn't make any sense to me as I am running this on the client.

**Comment by ollieread** [comment]
Well even when running locally, minecraft does have a server component, so you're technically not running it on just a client. `EntityClientPlayerMP` does mean client, but it does mean that the error is only happening client side, which is really quite weird.
